### ISSUE TITLE
Interesting..

### ISSUE THREAD

**Issue by zeke** [npm-dom/dom-stub#1]
@yoshuawuyts in what project are you using this? Have any code samples?

**Comment by yoshuawuyts** [comment]
Ohey! yeah, I just needed a stub equivalent that could be pulled through `is-dom`. I'm using it here: https://github.com/yoshuawuyts/virtual-raf/blob/master/test.js

**Comment by yoshuawuyts** [comment]
I didn't feel like plowing through `jsdom` for something that should only be a few lines of code. I can imagine that as people see other use cases it can be extended to look more like a proper html element.

**Comment by zeke** [comment]
nice. thanks for the code sample. :)

**Comment by yoshuawuyts** [comment]
^__^ no problem
